#!/bin/bash

# Limit number of processes ####################################################
#> if "OPERATING_SYSTEM" !~ /Cygwin|Darwin/
ulimit -u 2000
#> endif

# Disable history expansion ####################################################
#  "set +o histexpand" does not work, we use +H instead
set +H

# Redraw within TMUX: ##########################################################
# TODO: write "which" command for filepp!
if which resize 2>/dev/null >/dev/null; then
   trap 'eval $(resize)' WINCH
fi

# Disable ^S/^Q ################################################################
stty start '' stop ''

# vim: ft=sh
