background			=	default		default
frame				=	THEME_COLOR		default
window_title			=	white		default
directory			=	white		default
selected_directory		=	white		THEME_COLOR
file				=	THEME_COLOR		default bold
selected_file			=	white		THEME_COLOR
marked_file			=	white		default bold
marked_selected_file		=	white		THEME_COLOR bold
playlist			=	THEME_COLOR		default bold
selected_playlist		=	white		THEME_COLOR
info				=	THEME_COLOR		default bold
selected_info			=	white		THEME_COLOR bold
marked_info			=	THEME_COLOR		default bold
marked_selected_info		=	white		THEME_COLOR bold
empty_mixer_bar			= 	default		default
filled_mixer_bar		= 	white		THEME_COLOR bold
empty_time_bar			= 	default		default
filled_time_bar			= 	THEME_COLOR		THEME_COLOR bold
state				=	white		default bold
status				=	white		default
title 				=	THEME_COLOR		default bold
current_time			=	white		default
time_left			=	white		default
total_time			=	white		default
time_total_frames		=	THEME_COLOR		default
sound_parameters		=	white		default
legend				=	white		default
disabled			=	white		default
enabled				=	white		default bold
entry				=	white		default
entry_title			=	white		default bold
error				=	red		default
message				=	THEME_COLOR		default
plist_time			=	white		default bold
