#!/bin/bash

function picom9600() {
   picocom -b 9600  /dev/ttyUSB? --echo --imap lfcrlf "$@"
}

function picom4800() {
   picocom -b 4800  /dev/ttyUSB? --echo --imap lfcrlf "$@"
}

# TODO
# arduinoFlash() {
#    avrdude -c stk500v1 -P /dev/ttyUSB0 -p atmega328p -b 19200 -U flash:w:$1:i
# }
