#!/bin/bash

#> define IF_DIR(_IF_, _THEN_) [[ -d "_IF_" ]] && _THEN_

#> define PATH_PREPEND(_DIR_) PATH="_DIR_:$PATH"
#> define PATH_APPEND(_DIR_)  PATH+=":_DIR_"

#> define PREPEND_IF(_DIR_) IF_DIR(_DIR_, PATH_PREPEND(_DIR_))
#> define APPEND_IF(_DIR_)  IF_DIR(_DIR_, PATH_APPEND(_DIR_))

export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/games:/opt"

# arch linux
#  export PATH='/bin:/usr/local/bin:/usr/local/sbin'

PATH_PREPEND($HOME/bin)
PATH_PREPEND($HOME/scripts)
PATH_PREPEND(/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/share/perl5/vendor_perl)
PATH_PREPEND(GEMPATH)
PATH_APPEND(/opt/vc/bin)
PATH_APPEND($HOME/pscripts)

# vim: ft=sh
