defines:
  THEME_COLOR: "blue"

  DEFAULT_SHELL: |
    SHELL:
      if type zsh >/dev/null 2>/dev/null; then
        echo /bin/zsh
      elif type bash >/dev/null 2>/dev/null; then
        echo /bin/bash
      else
        echo /bin/sh
      fi

  HAVE_DEV_SHM: |
    SHELL:
      test -d /dev/shm && echo 1 || echo 0

filepp_modules: ["bigdef.pm", "function.pm", "hash-comment.pm", "remove-empty-lines.pm"]

apply: |
  echo "Reloading tmux conf ..." >&2
  tmux source ~/.tmux.conf && echo DONE || echo FAILED
