menu	THEME_COLOR	THEME_BACKGROUND

hotkey	THEME_COLOR	THEME_BACKGROUND

axis	default	THEME_BACKGROUND

track	THEME_COLOR	THEME_BACKGROUND

handle	white	THEME_BACKGROUND

play	green	THEME_BACKGROUND

record	red	THEME_BACKGROUND

active	white	THEME_COLOR
